language: node_js

services:
  - docker

addons:
  ssh_known_hosts:
    - $PUBLICIP

before_install:
  - pip install --user awscli

install: skip

script:
  - docker build -t hmarks/quiz_app:$TRAVIS_BUILD_NUMBER .
  - bash ./scripts/docker_push.sh

before_deploy:
  provider: script
  script:
    - cd $TRAVIS_BUILD_DIR
    - chmod +x ./scripts/aws.sh
    - bash ./scripts/aws.sh

deploy:
  provider: script
  script: bash deploy.sh
