language: node_js

services:
  - docker

addons:
  ssh_known_hosts:
    - $PUBLICIP

install:
  - pip install --user awscli

script:
  - docker build -t hmarks/quiz_app:$TRAVIS_BUILD_NUMBER .
  - bash ./scripts/docker_push.sh
  - bash ./scripts/aws.sh

deploy:
  provider: script
  script: bash deploy.sh
