language: node_js

services:
  - docker

addons:
  ssh_known_hosts:
    - $PUBLICIP

before_install:
  - pip install --user awscli

install: skip

script:
  - docker build -t hmarks/quiz_app:$TRAVIS_BUILD_NUMBER .
  - bash ./scripts/docker_push.sh
  - bash ./scripts/aws.sh
    #before_deploy:
    #provider: script
    #script:

deploy:
  provider: script
  script: bash deploy.sh
